#!/bin/bash

# export GPIO pins for the servo power and set initial value
while read io val ; do
	# export the io pin if it does not yet exist
    [ ! -d /sys/class/gpio/gpio$io ] && echo $io > /sys/class/gpio/export
    echo out > /sys/class/gpio/gpio$io/direction
    echo $val > /sys/class/gpio/gpio$io/value
done << HERE
25 1
21 1
HERE


#Power monitor
while true
do
	current_voltage=`cat /sys/class/power_supply/max1720x_battery/voltage_avg`
	if [ $current_voltage -le 6500 ]; then
		echo 0 > /sys/class/gpio/gpio25/value
		echo 0 > /sys/class/gpio/gpio21/value
		mpg123 -q /home/ubuntu/Music/low_power.mp3
	fi
	sleep 8
done
